using System;
using System.IO;
using System.Text;

namespace Rmount
{
	/// <summary>
	/// Manages application configuration stored in INI file
	/// </summary>
	public class AppConfig
	{
		private const string CONFIG_FILE = "Rmount.ini";

		public string Rclone { get; set; }

		public string Config { get; set; }

		public bool AutoStart { get; set; }

		public AppConfig()
		{
			// Set defaults using portable-first approach
			Rclone = FindRcloneExecutable();
			Config = FindRcloneConfig();
			AutoStart = false;
		}

		/// <summary>
		/// Get the path to the configuration file
		/// </summary>
		public static string GetConfigFilePath()
		{
			string exeDir = AppDomain.CurrentDomain.BaseDirectory;
			return Path.Combine(exeDir, CONFIG_FILE);
		}

		/// <summary>
		/// Find rclone.exe - portable-first approach
		/// Search order:
		/// 1. Program directory
		/// 2. System PATH
		/// </summary>
		private static string FindRcloneExecutable()
		{
			string exeDir = AppDomain.CurrentDomain.BaseDirectory;

			// 1. Check program directory first (portable)
			string localPath = Path.Combine(exeDir, "rclone.exe");
			if (File.Exists(localPath))
			{
				return localPath;
			}

			// 2. Return relative path (will be checked in PATH later)
			return "rclone.exe";
		}

		/// <summary>
		/// Find rclone.conf - portable-first approach
		/// Search order:
		/// 1. Program directory
		/// 2. C:\Users\<USERNAME>\.config\rclone\
		/// 3. %APPDATA%\rclone\
		/// </summary>
		private static string FindRcloneConfig()
		{
			string exeDir = AppDomain.CurrentDomain.BaseDirectory;
			string userName = Environment.UserName;

			// 1. Check program directory first (portable)
			string localPath = Path.Combine(exeDir, "rclone.conf");
			if (File.Exists(localPath))
			{
				return localPath;
			}

			// 2. Check C:\Users\<USERNAME>\.config\rclone\
			string userConfigPath = Path.Combine("C:", "Users", userName, ".config", "rclone", "rclone.conf");
			if (File.Exists(userConfigPath))
			{
				return userConfigPath;
			}

			// 3. Check %APPDATA%\rclone\
			string appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
			string appDataConfigPath = Path.Combine(appDataPath, "rclone", "rclone.conf");
			if (File.Exists(appDataConfigPath))
			{
				return appDataConfigPath;
			}

			// Default to program directory for new installations (portable)
			return localPath;
		}

		/// <summary>
		/// Load configuration from INI file
		/// </summary>
		public static AppConfig Load()
		{
			var config = new AppConfig();
			string configFile = GetConfigFilePath();

			if (!File.Exists(configFile))
			{
				return config;
			}

			try
			{
				string[] lines = File.ReadAllLines(configFile);
				foreach (string line in lines)
				{
					string trimmed = line.Trim();

					// Skip comments and empty lines
					if (string.IsNullOrWhiteSpace(trimmed) || trimmed.StartsWith("#") || trimmed.StartsWith(";"))
					{
						continue;
					}

					// Parse key=value
					int equalIndex = trimmed.IndexOf('=');
					if (equalIndex > 0)
					{
						string key = trimmed.Substring(0, equalIndex).Trim();
						string value = trimmed.Substring(equalIndex + 1).Trim();

						switch (key.ToLower())
						{
							case "rclone":
								config.Rclone = value;
								break;

							case "config":
								config.Config = value;
								break;

							case "autostart":
								config.AutoStart = value.ToLower() == "true" || value == "1";
								break;
						}
					}
				}
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"Error loading config: {ex.Message}");
			}

			return config;
		}

		/// <summary>
		/// Save configuration to INI file
		/// </summary>
		public void Save()
		{
			string configFile = GetConfigFilePath();

			try
			{
				var sb = new StringBuilder();
				sb.AppendLine("# Rmount Configuration");
				sb.AppendLine("# This file is automatically generated");
				sb.AppendLine();
				sb.AppendLine("# Path to rclone.exe (can be absolute or relative)");
				sb.AppendLine($"Rclone={Rclone}");
				sb.AppendLine();
				sb.AppendLine("# Path to rclone.conf configuration file");
				sb.AppendLine($"Config={Config}");
				sb.AppendLine();
				sb.AppendLine("# Enable autostart with Windows (true/false)");
				sb.AppendLine($"AutoStart={AutoStart.ToString().ToLower()}");

				File.WriteAllText(configFile, sb.ToString(), Encoding.UTF8);
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine($"Error saving config: {ex.Message}");
			}
		}

		/// <summary>
		/// Check if the configuration is valid
		/// </summary>
		public bool IsValid()
		{
			// Check if rclone executable exists
			if (!File.Exists(Rclone))
			{
				// Try to find it in PATH
				string foundPath = FindInPath("rclone.exe");
				if (foundPath != null)
				{
					Rclone = foundPath;
				}
				else
				{
					return false;
				}
			}

			// Config path doesn't need to exist yet (rclone config will create it)
			// But the directory should be valid
			try
			{
				string dir = Path.GetDirectoryName(Config);
				if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
				{
					// Directory doesn't exist, but we can try to create it
					Directory.CreateDirectory(dir);
				}
			}
			catch
			{
				return false;
			}

			return true;
		}

		/// <summary>
		/// Find an executable in the system PATH
		/// </summary>
		private string FindInPath(string filename)
		{
			string path = Environment.GetEnvironmentVariable("PATH");
			if (string.IsNullOrEmpty(path))
			{
				return null;
			}

			string[] directories = path.Split(';');
			foreach (string dir in directories)
			{
				try
				{
					string fullPath = Path.Combine(dir.Trim(), filename);
					if (File.Exists(fullPath))
					{
						return fullPath;
					}
				}
				catch
				{
					// Skip invalid paths
				}
			}

			return null;
		}
	}
}